/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as GamesRandomiserImport } from './routes/games/randomiser'

// Create Virtual Routes

const GamesIndexLazyImport = createFileRoute('/games/')()
const AppsIndexLazyImport = createFileRoute('/apps/')()
const AuthenticatedIndexLazyImport = createFileRoute('/_authenticated/')()
const AuthenticatedProfileLazyImport = createFileRoute(
  '/_authenticated/profile',
)()
const AuthenticatedAboutLazyImport = createFileRoute('/_authenticated/about')()
const AppsWeightIndexLazyImport = createFileRoute('/apps/weight/')()
const AppsRecipesIndexLazyImport = createFileRoute('/apps/recipes/')()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const GamesIndexLazyRoute = GamesIndexLazyImport.update({
  path: '/games/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/games/index.lazy').then((d) => d.Route))

const AppsIndexLazyRoute = AppsIndexLazyImport.update({
  path: '/apps/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/apps/index.lazy').then((d) => d.Route))

const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)

const AuthenticatedProfileLazyRoute = AuthenticatedProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/profile.lazy').then((d) => d.Route),
)

const AuthenticatedAboutLazyRoute = AuthenticatedAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/about.lazy').then((d) => d.Route),
)

const GamesRandomiserRoute = GamesRandomiserImport.update({
  path: '/games/randomiser',
  getParentRoute: () => rootRoute,
} as any)

const AppsWeightIndexLazyRoute = AppsWeightIndexLazyImport.update({
  path: '/apps/weight/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/apps/weight/index.lazy').then((d) => d.Route),
)

const AppsRecipesIndexLazyRoute = AppsRecipesIndexLazyImport.update({
  path: '/apps/recipes/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/apps/recipes/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/games/randomiser': {
      id: '/games/randomiser'
      path: '/games/randomiser'
      fullPath: '/games/randomiser'
      preLoaderRoute: typeof GamesRandomiserImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/apps/recipes/': {
      id: '/apps/recipes/'
      path: '/apps/recipes'
      fullPath: '/apps/recipes'
      preLoaderRoute: typeof AppsRecipesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/apps/weight/': {
      id: '/apps/weight/'
      path: '/apps/weight'
      fullPath: '/apps/weight'
      preLoaderRoute: typeof AppsWeightIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedAboutLazyRoute,
    AuthenticatedProfileLazyRoute,
    AuthenticatedIndexLazyRoute,
  }),
  GamesRandomiserRoute,
  AppsIndexLazyRoute,
  GamesIndexLazyRoute,
  AppsRecipesIndexLazyRoute,
  AppsWeightIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/games/randomiser",
        "/apps/",
        "/games/",
        "/apps/recipes/",
        "/apps/weight/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/about",
        "/_authenticated/profile",
        "/_authenticated/"
      ]
    },
    "/games/randomiser": {
      "filePath": "games/randomiser.tsx"
    },
    "/_authenticated/about": {
      "filePath": "_authenticated/about.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/apps/": {
      "filePath": "apps/index.lazy.tsx"
    },
    "/games/": {
      "filePath": "games/index.lazy.tsx"
    },
    "/apps/recipes/": {
      "filePath": "apps/recipes/index.lazy.tsx"
    },
    "/apps/weight/": {
      "filePath": "apps/weight/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
